services:
  web:
    #image: gavinlon/magic-stream-web-prod:1.0.0
    image: nate247/magic-stream-web-prod:${IMAGE_TAG:-latest}
    container_name: magic-stream-web-prod

    ports: 
      - "8081:80"
    restart: always

  api:
    #image: gavinlon/magic-stream-api-prod:1.0.0
    image: nate247/magic-stream-api-prod:${IMAGE_TAG:-latest}
    container_name: magic-stream-api-prod
    
    restart: always
